# Generated by Django 4.1.13 on 2024-02-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interested_countries',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='travel.country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_countries',
            field=models.ManyToManyField(blank=True, related_name='users', to='travel.country'),
        ),
    ]
