# Generated by Django 4.1.13 on 2024-02-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_userprofile_interested_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
    ]
