# Generated by Django 4.1.13 on 2023-12-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_localplace_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localplace',
            old_name='name',
            new_name='country',
        ),
        migrations.AddField(
            model_name='localplace',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
