# Generated by Django 4.1.13 on 2023-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_userprofile_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interests_users', to='travel.localplace'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visited_countries',
            field=models.ManyToManyField(blank=True, related_name='visited_users', to='travel.localplace'),
        ),
    ]
