# Generated by Django 4.1.13 on 2023-12-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_userprofile_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localplace',
            name='attractions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localplace',
            name='nature_views',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localplace',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
