# Generated by Django 4.2.5 on 2023-12-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_remove_localplace_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='localplace',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
