# Generated by Django 4.1.13 on 2024-02-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_localplace_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_background',
            field=models.ImageField(blank=True, null=True, upload_to='profile_backgrounds/'),
        ),
    ]
