# Generated by Django 4.1.13 on 2024-02-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_userprofile_profile_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='planned_countries',
            field=models.ManyToManyField(related_name='planned_by', to='travel.country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visited_countries',
            field=models.ManyToManyField(related_name='visited_by', to='travel.country'),
        ),
    ]
